### ISSUE TITLE
[Enhancement Request] NEEDS using subdirectories

### ISSUE THREAD

**Issue by jrossignol** [sarbian/ModuleManager#108]
I may have a use case for Contract Configurator contracts where I want to do something different with/without the Making History expansion.  It would be ideal if I had an easy module manager way to do this with a `NEEDS` check.  Right now I could technically do `NEEDS[SquadExpansion]`, but we have to assume that there will be more expansions in future (Take 2 need their cheddar).

My suggestion for how to solve this would be to implement something that allows me to do `NEEDS[SquadExpansion/MakingHistory]`.  I realize that something like this has been requested and rejected in the past (since the "mods by directory" list is built up front), so I'd be fine if this was something that was done specifically for the SquadExpansion directory as an exception.  Of course if you're adding exceptions, I'd also ask that you consider putting ContractPacks as an exception as well as I have users that would want to do `NEEDS[ContractPacks/foo]`.

**Comment by blowfishpro** [comment]
I've been thinking about this too, I think this is a good idea.  I think it's simple enough to say that if the string contains a `/` then it will check needs by looking for that path inside GameData

**Comment by theonegalen** [comment]
I will also use this.

**Comment by fwdixon** [comment]
So ran in to an issue: I am adding the "Kerbin Program" as the first Celestial Body Program (the manned ones). 

I can get it to show up in the admin building, but it creates 17 copies of it (1 for every body in the kerbal system). Here is the code for the first part of the Strategy definition in the .cfg file:

`   name = KerbinProgram
    id = KerbinProgram

    title = The $homeWorld Program
    title
    {
        Earth = The Mercury Program
    }
    desc = For generations we've stared at the stars, now we want to go there! But some say $body is flat and those little white dots are painted on a dome. Let's find out!
    department = Crewed Missions
    icon = Strategia/icons/LocalScience1


    groupTag = CelestialBodyProgram,A`

If I replace $homeWorld with $body, then instead of the admin building showing 17 copies of "The Kerbin Program", each copy has the name of a different body in the system.

I looked at the source code for CelestialBodyProgram.cs and noticed there is a class defined for each of the current program types (moon, planet, gas giant). Would a new class need to be created for Kerbin or is there a way to work around this in the config files?
