### ISSUE TITLE
Checking pass-order as intended?

### ISSUE THREAD

**Issue by pjf** [sarbian/ModuleManager#28]
Hey Sarbian,

I'm very sorry to trouble you, but I'm in the process of writing a bunch of ModuleManager tutorials¹, as I keep finding myself needing to reference the same things over and over again, and assume other folks therefore must also do the same.

I'm wanting to check the pass order run by MM is "as intended". In particular, where a set of patches run depends on on if a mod has a `.dll` or not. I keep being surprised when `AIES_Aerospace` runs after `RealismOverhaul`, because the first doesn't have a `.dll`, and the second does.

At first glance these doesn't feel right; if AIES releases with a `.dll` in the future, then the run ordering changes, and folks writing MM `.cfgs` need to know if their target bundles a `.dll` or not. (This came up because `RealismOverhaul` clearly thought it was running after the AIES pass, but instead runs before it.)

If this is as-intended, I can say so in the tutorials. If not, then I can say the behaviour may change.

Many, many thanks!

~ Paul

---

¹ The tutorials are being written as part of my work on The Kerbal Book, which means they may take a little time to finish, but I can assure you they'll be unencumbered when they are.

**Comment by pjf** [comment]
Also, for my own reference, this is how I currently see which passes are being run, and in which order:

`ack "\[ModuleManager\] Applying" Player.log | perl -nE'say $1 if /(:(?:BEFORE|FOR|AFTER)\[[^]]+\])/i' | uniq | less`

**Comment by sarbian** [comment]
Hi Paul,

Clear issues are always welcome here.
I had a quick look at the code and MM fills the list in 3 steps 
 - dll names
 - :FOR[xxx] in cfg
 - top directories names
 
So they are clearly not in a logical order and that does not serve any purpose.

I will replace the List with a SortedList in the next version to make sure the order is more logical. And I will cleanup some of that code since it looks way more complex than it should.
 
Book ! Ping me when it is ready :)

Sarbian
